
ingress:
  className: nginx
  hosts:
    - host: folio.local
      paths:
        - path: /
          pathType: Prefix

folio:
  auth:
    keycloak:
      clientSecret: VDyLEjGR3xDQvoQlrHq5AB6OwbW0Refc
